openapi: 3.0.0
info:
  title: Authenticate with Wechat MP!
  version: 0.0.1
servers:
- url: https://virtserver.swaggerhub.com/UniHeart/wechat-mp/0.0.1
  description: SwaggerHub API Auto Mocking
- url: http://localhost:8080
paths:
  /mp-qr:
    get:
      tags:
      - mp-qr
      summary: Gets a temporary qr code with parameter
      operationId: mp-qr-url
      responses:
        "200":
          description: Got the temporary qr code image link
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MpQR'
              example:
                expire_seconds: 60
                imageUrl: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=gQGT7zwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAycnE3QWw3b3JmazMxb2FMQnh3Y1UAAgTOrmVgAwQ8AAAA
                sceneId: 66afab27-c8fa-417d-a28a-95d5a977e1d3
                ticket: gQGT7zwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAycnE3QWw3b3JmazMxb2FMQnh3Y1UAAgTOrmVgAwQ8AAAA
                url: http://weixin.qq.com/q/02rq7Al7orfk31oaLBxwc
components:
  schemas:
    MpQR:
      type: object
      properties:
        expire_seconds:
          type: integer
          format: int64
          example: 60
        imageUrl:
          type: string
          example: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=gQGT7zwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAycnE3QWw3b3JmazMxb2FMQnh3Y1UAAgTOrmVgAwQ8AAAA
        sceneId:
          type: string
          example: 66afab27-c8fa-417d-a28a-95d5a977e1d3
        ticket:
          type: string
          example: gQGT7zwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAycnE3QWw3b3JmazMxb2FMQnh3Y1UAAgTOrmVgAwQ8AAAA
        url:
          type: string
          example: http://weixin.qq.com/q/02rq7Al7orfk31oaLBxwc
