openapi: 3.0.0
info:
  title: Authenticate with Wechat MP!
  version: 0.0.1
servers:
- url: https://virtserver.swaggerhub.com/UniHeart/wechat-mp/0.0.1
  description: SwaggerHub API Auto Mocking
- url: http://localhost:8080
paths:
  /mp-qr:
    get:
      tags:
      - mp-qr
      summary: Gets a temporary qr code with parameter
      operationId: mp-qr-url
      responses:
        "200":
          description: Got the temporary qr code image link
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MpQR'
              example:
                expire_seconds: 60
                imageUrl: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=gQGT7zwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAycnE3QWw3b3JmazMxb2FMQnh3Y1UAAgTOrmVgAwQ8AAAA
                sceneId: 66afab27-c8fa-417d-a28a-95d5a977e1d3
                ticket: gQGT7zwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAycnE3QWw3b3JmazMxb2FMQnh3Y1UAAgTOrmVgAwQ8AAAA
                url: http://weixin.qq.com/q/02rq7Al7orfk31oaLBxwc
  /mp-qr-scan-status:
    get:
      tags:
      - mp-qr
      summary: Get the scanning status of qr code
      operationId: mp-qr-scan-status
      parameters:
      - name: ticket
        in: query
        description: the ticket for the qr code to query scanning status
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: gQE48DwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAyb2U4U2wwb3JmazMxcS1kQ3h3YzgAAgSCjWZgAwQ8AAAA
      responses:
        "200":
          description: The scanning stqtus of qr code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MpQRScanStatus'
              example:
                openId: oWFvUw5ryWycy8XoDCy1pV0SiB58
                status: SCANNED
  /mp-message:
    post:
      tags:
      - mp-qr
      summary: Receive xml messages sent from wechat mp server
      operationId: mp-message
      requestBody:
        description: wechat mp messages in xml format
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/xml'
        required: true
      responses:
        "200":
          description: the message was well received
components:
  schemas:
    MpQR:
      type: object
      properties:
        expire_seconds:
          type: integer
          format: int64
          example: 60
        imageUrl:
          type: string
          example: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=gQGT7zwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAycnE3QWw3b3JmazMxb2FMQnh3Y1UAAgTOrmVgAwQ8AAAA
        sceneId:
          type: string
          example: 66afab27-c8fa-417d-a28a-95d5a977e1d3
        ticket:
          type: string
          example: gQGT7zwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAycnE3QWw3b3JmazMxb2FMQnh3Y1UAAgTOrmVgAwQ8AAAA
        url:
          type: string
          example: http://weixin.qq.com/q/02rq7Al7orfk31oaLBxwc
    MpQRScanStatus:
      type: object
      properties:
        openId:
          type: string
          example: oWFvUw5ryWycy8XoDCy1pV0SiB58
        status:
          type: string
          example: SCANNED
    xml:
      type: object
      properties:
        ToUserName:
          type: string
          example: oWfv
        FromUserName:
          type: string
          example: "1234"
        CreateTime:
          type: number
          example: 1357290913
        MsgType:
          type: string
          example: Text
        Event:
          type: string
          example: subscribe
        EventKey:
          type: string
          example: qrscene_123123
        Ticket:
          type: string
          example: TICKET
